<?php
/**
 * Product:     Advanced Permissions
 * Package:     Aitoc_Aitpermissions_2.2.4_2.0.3_90233
 * Purchase ID: xFF945pgbyDre0fKeBvM8FAv6R2a0C65GbaW0cwEpD
 * Generated:   2011-07-05 15:42:56
 * File path:   app/design/frontend/default/default/template/aitpermissions/lfooter.phtml
 * Copyright:   (c) 2011 AITOC, Inc.
 */
?>
<?
/**
 * @copyright  Copyright (c) 2009 AITOC, Inc. 
 */
?>
<!-- wlpvymxidlzjdxezhyescgtnfblxquji -->