<?php
    $_item = $this->getItem();
    $rowClass = (Mage::getSingleton('jewellery/session')->getCartItemPosition() % 2 === 0) ? 'even' : '';
    $jSession = Mage::getSingleton('jewellery/session');
    $cSession = Mage::getSingleton('checkout/session');
    $newArray = $cSession->getData('newProducts');
    if (! $newArray) {
        $newArray = array();
    }

    $invData = Mage::helper('jewellery_catalog')->getInventoryData($this->getProduct());
	$quickUrl = $this->getQuickViewUrl();
?>

<tr class="<?php echo $rowClass; echo (in_array($this->getProduct()->getId(), $newArray) || $_item->isNewProduct) ? ' new-product-item' : ''; echo $_item->isNewProduct ? ' newProductFromAjax ' : ''; ?>">
    <td>
			<?php if ($this->hasProductUrl() && $quickUrl):?>
				<a href="<?php echo $quickUrl ?>" title="<?php echo $this->htmlEscape($this->getProductName()) ?>" class="product-image ajax"><?php endif;?>
						<img src="<?php echo $this->getProductThumbnail()->resize(57,57); ?>" width="57" height="57" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" />
				<?php if ($this->hasProductUrl() && $quickUrl):?></a><?php endif;?>
	</td>
    <td>
        <?php if ($this->hasProductUrl()):?>
            <a href="<?php echo $this->getProductUrl() ?>"><?php echo $this->htmlEscape($this->getProductName()) ?></a>
        <?php else: ?>
            <?php echo $this->htmlEscape($this->getProductName()) ?>
        <?php endif; ?>

        <?php echo $this->getProduct()->getSku(); ?>

        <?php if ($_options = $this->getOptionList()):?>
        <dl class="item-options">
            <?php foreach ($_options as $_option) : ?>
            <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
            <dt><?php echo $this->htmlEscape($_option['label']) ?>: </dt>
            <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>><?php echo $_formatedOptionValue['value'] ?>
                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                <div class="truncated_full_value">
                    <dl class="item-options">
                        <dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
                        <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                    </dl>
                </div>
                <?php endif; ?>
            </dd>
            <?php endforeach; ?>
        </dl>
        <?php endif;?>

        <?php if (($vpe = $this->helper('catalog/output')->productAttribute($this->getProduct(), $this->getProduct()->getVerpackungseinheitVe(), 'verpackungseinheit_ve')) > 1) : ?>
        <dl class="item-options">
            <dt><?php echo $this->__('Unit'); ?>: </dt>
            <dd><?php echo $this->__('%d Pieces', $vpe); ?></dd>
        </dl>
        <?php endif; ?>

    </td>
    <td class="delete"><a href="<?php echo $this->getDeleteUrl($_item->isNewProduct === true)?>" class="delete-link"></a></td>

    <td><span class="lager <?php echo $invData['status']; ?>" title="<?php echo $this->__($invData['status']); ?>"></span></td>

	<?php 
		if (! $_item->isNewProduct) {
			$func1 = "javascript:del('qty-cart{$_item->getId()}')";
			$func2 = "javascript:add('qty-cart{$_item->getId()}')";
		} else {
			$func1 = "javascript:addToCartM(this)";
			$func2 = "javascript:addToCartP(this)";
		}
	?>

    <td class="amount">
        <span class="qty-minus" onClick="<?php echo $func1 ?>"></span>
        <input size="1" value="<?php echo $this->getQty(); ?>"  name="cart[<?php echo $_item->getId() ?>][qty]" id="qty-cart<?php echo $_item->getId() ?>" class="product-qty" />
        <span class="qty-plus" onClick="<?php echo $func2 ?>"></span>
        <span class="update-cart" onClick="updateCartForm.submit()" title="<?php echo $this->__('Update Shopping Cart') ?>"></span>
<?php /* ?>        
        <select name="cart[<?php echo $_item->getId() ?>][qty]" onchange="updateCartForm.submit()">
            <?php for ($_qty = 0; $_qty <= $invData['qty']; $_qty++) : ?>
                <option value="<?php echo $_qty; ?>"<?php if ($this->getQty() == $_qty) : ?> selected="selected"<?php endif; ?>><?php echo $_qty; ?></option>
            <?php endfor; ?>
         </select>
<?php */ ?>    
    
    </td>

    <td class="align-center">
        <span class="cart-price">
            <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
        </span>
    </td>

    <td class="align-center">
        <span class="cart-price">
            <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>
        </span>
    </td>

</tr>
