 <h2 style="text-align:center; color:#FF6300;">AITOC, Inc. License Agreement for Magento Extensions.</h2>
    <h3>1. Definitions</h3>
    <p>The following definitions shall apply to this License Agreement: 
        <ul>
            <li>&#8220;Vendor&#8221; or &#8220;Licensor&#8221; means AITOC Inc., a producer of extensions for Magento and owner of all rights for these extensions.</li>
            <li>&#8220;Customer&#8221;, &#8220;Licensee" and &#8220;Client&#8221; means a company or a person, who purchases Magento extensions.</li>
            <li>&#8220;Product&#8221; and &#8220;Extension&#8221; means Magento extension, property of AITOC Inc.</li>
            <li>&#8220;Segmented Product/Extension&#8221; means a Magento extension which price depends on the number of certain parameters specified in the License option (Products, Stores or Admins). </li>
            <li>&#8220;Magento&#8221; means eCommerce software written in PHP which the Products are to work with.</li>
            <li>&#8220;License&#8221; means a digital document which grants permission to use Product within the specified License Agreement and which contains all necessary Client's domain information.</li>
            <li>&#8220;Installation&#8221; means placing the Product on an operational Magento solution to be run.</li>
            <li>&#8220;Derivative Works&#8221; means a work and/or a document that is based upon one or more preexisting works such as a revision, modification, translation, abridgment, condensation, expansion or any other form in which such a preexisting work may be recast, transformed or adapted, and that, if prepared without authorization by the owner of the preexisting work, would constitute copyright infringement.</li>
            <li>&#8220;Use&#8221; means executing or loading Product functions, and copying the Product for archival or emergency restart purposes.</li>
        </ul>
    </p>
    
    <h3>2. General</h3>
    <p>This is a legal Agreement between Customer and Vendor that covers Customer’s purchase and use of the Product. By purchasing the Product Customer is asserting with the below-stated Terms and Conditions of the present Agreement. Any violation of set forth below Terms and Conditions will automatically deprive the Customer of the right to use the Product, thus the Customer must cease using it and terminate all copies and derivatives of the Product at Customer’s disposal.</p>
    
    <h3>3. License</h3>
    <h4 style="padding-left:20px;">3.1. General Issues</h4>
    <p>By purchasing the Product Customer obtains a License, which will remain valid until the Licensee stops 
using the Product or until Licensor terminates this License because of Licensee's failure to comply with 
any of its Terms and Conditions.</p>

    <p>AITOC offers a <strong>Single Installation License</strong> for Magento extensions. Each extension can be used on 
one Magento installation. The installation location must always be that entered in the user database 
and not a mirror or redirect to it. Entering incorrect information can cause License revocation. </p>

    <p>A sold License does not include ownership of any original works, part of thereof or any documentation 
or derivative works of the Product.</p>

    <h4 style="padding-left:20px;">3.2. License for Segmented Products</h4>
    
    <p>Some of AITOC Products are Segmented. This means their price depends on the number of certain 
parameters specified in the License option (Products, Stores or Admins) which were selected during 
the purchase. Segmented Products include necessary controlling functionality to provide the Customer 
with the exact number of parameters. The functionality will make sure the Customer does not exceed 
the allowed number of parameters. When reaching the parameters limit, the Customer can not extend 
the limitation until upgrading the License.</p>

    <p>Downgrades are not possible via standard License upgrade functionality. For downgrades, please refer 
to AITOC, Inc. for a Refund. Please note that all Refunds, including downgrades, are only possible 
within the 30-day period from the initial purchase date. The Client has an option to delete Product’s 
License via Magento Administrator Control Panel.</p>

    <p>Editing License file in any way other than via Administrator Control Panel User Interface will result in 
License revocation and Product’s incorrect operation. AITOC doesn’t bear any responsibility for any 
personal or business data loss or damaging of site in case of License functionality editing attempts. </p>

    <h3>4. Copyright</h3>
    
    <p>Any unauthorized copying, reselling, renting, leasing, sublicensing, pledging, conveying, transferring of 
rights, creating of any Derivative Works, or disclosing of modification source codes in any way, porting 
of Product to other platforms and content management systems without prior written approval from 
AITOC Inc. is prohibited.</p>

    <p>Proofs of copyright infringement include, but are not limited to, similar code style and structures and 
containing similar to Product source code, layout and design.<br />
Customer is not allowed to remove the original AITOC Inc. copyright inscription from the source code 
of the Product. Modifications of the source code are allowed, but at own risk.</p>
    
    <p>If revealed that the Product is used in breach of the above mentioned terms of use, AITOC, Inc. is 
authorized to suspend the license, advising the Customer on what actions are required to resolve the 
matter. In cases of a severe or repetitive violation where advice has been ignored, AITOC Inc. is 
authorized to revoke the License. </p>
    
    <p>The source code and files are exclusively owned by AITOC Inc. and are subject to US Copyright Law 
and Copyright Laws of the State of Delaware, as well as international copyright treaty provisions. 
AITOC Inc. retains title to and ownership of the Product and all enhancements, modifications and 
updates of the Product.</p>

    <p>The exclusive forum for disputes arising out of, or relating to, this Agreement shall be an appropriate 
federal or state court in the county of New Castle, Delaware.</p>

    <h3>5. Installation</h3>
    
    <h4 style="padding-left:20px;">5.1. Generic Installation Issues</h4>
    
    <p>Each Product package includes an automated Installer. The automated installation may depend on 
configuration of operational Magento solution. AITOC Inc. does not pledge for its installation module to 
operate successfully on modified as well as non-modified Magento solution. In case of any problems 
with automatic installation the Customer may purchase installation service executed by Vendor’s staff. 
To use the paid installation service Client is obliged to present correct web-site access information for 
Vendor’s support personnel, as well as valid Product License information. Installation service payments 
are non-refundable.<br />
    Failing to meet any of the above mentioned requirements deprives Customer of ability to use this 
service.</p>

    <h4 style="padding-left:20px;">5.2. Segmented Product Installation</h4>
    
    <p>Each Segmented Product package includes an automated Installer and a License file. License file 
contains necessary data which is passed to AITOC web-server for validation of Client’s purchase and 
License parameters. After the necessary data is collected and proved valid, AITOC web-server sends 
an XML file which makes it possible to install the Product.</p>
    
    <p>Client’s License and Magento URL is placed in AITOC customer Database for future support and 
purchase validation. AITOC, Inc. doesn’t collect any personal or business information, except for the 
information in its Modules that ensures the Module’s valid purchase and exploitation. Please refer to 
the Confidentiality paragraph of this agreement for more details.</p>

    <h3>6. Product Support Policy</h3>
    
    <p>Free support period for one Product totals 6 months starting from the purchase date of the Product. 
The term of free support can be prolonged when a Product update is purchased. It is described in more 
detail in the Product Updates section.</p>

    <p>Support team shall provide to Customer, without additional charge, all reasonably necessary written 
consultation requested in connection with use and operation of the Product or any problems therewith, 
within above-stated period of time.</p>

    <p>Free support does not include achieving compatibility with third party solutions and is not provided if 
the Product has been customized. In cases when extraordinary support efforts will be required 
Customer will be offered either paid support service or refund of the Product cost. 
Under extraordinary support efforts AITOC, Inc. supposes a request which probable cost to resolve 
may exceed the cost of the purchased Product. Support costs are calculated in accordance with 
average US market rates.</p>

    <p>Support team preserves the right to ignore any appeals or requests, not falling under the present 
conditions.<br />
    All information, acquired from AITOC, Inc. support team is advisory only and shall not create any 
warranty for AITOC Inc.</p>

    <h3>7. Service Level Agreement</h3>
    
    <p>AITOC, Inc. will provide support services via support tickets system on the products’ pages Monday &#8212; 
Friday, 8 am &#8212; 5 pm GMT (3 am &#8212; 12 pm EST).</p>
    
    <h3>8. Product Updates</h3>
        
    <h4 style="padding-left:20px;">8.1 General issues</h4>
        
    <p>AITOC will timely release the information about new updates in the Changelog tab on the Product 
page. It is Customer’s responsibility to check for updates availability. Customer can claim updates via 
Support department. </p>

    <p>All updates can be used only as a replacement of a previously purchased Product, not as a separate 
copy of a Product.</p>

    <p>AITOC reserves the right to determine which products will be updated and when. AITOC reserves the 
right to discontinue product updates.</p>

    <h4 style="padding-left:20px;">8.2 Product Updates within similar licensing scheme</h4>
    
    <p>Updates shall be available to the Customer free of charge for 6 months from the original purchase 
date. After that an update would cost 75% of the current product price.</p>

    <p>For segmented Products, discount is only applied to the same License option. If needed, Upgrade of 
Segmented License can be performed before or after buying a Product update. </p>

    <p>Paid update package includes: the latest version of the product, 6 extra months of free updates and 
support from the purchase date. </p>

    <p>Customer is not obliged to purchase updates every 6 months. The decision about whether to purchase 
an update and when is solely Customer’s right. Customer can continue using the Product after 6 
months from the original purchase date and can contact AITOC for paid support services. </p>

    <h4 style="padding-left:20px;">8.3 Product Updates within different licensing schemes</h4>
    
    <p>If Client purchased a Product under Simple License and AITOC has transferred the Product into 
Segmented Licensing, then</p>

    <h4 style="padding-left:20px;">8.3.1 Update claimed during a 6-months period from the original purchase date</h4>
    
    <p>Update claimed during a 6-months period from the original purchase date is provided with a discount 
equal to the price the Customer originally paid for the Product with Simple License with extra 
25% discount for any License option. The paid update includes the latest version of the product, 
6 extra months of free updates and support from the purchase date. </p>

    <h4 style="padding-left:20px;">8.3.2 Update claimed after a 6-months period from the original purchase date</h4>
    
    <p>Update claimed after a 6-months period from the original purchase date is provided with a 25% 
discount for any License option. The paid update includes the latest version of the product, 6 
extra months of free updates and support from the purchase date. </p>

    <h3>9. Refunds</h3>
    
    <p>Customer may demand a refund for any AITOC Inc. Product within a 30-day period from the date of 
purchase. Any clarification of Customer's refund claim within the 30-days period is optional.
AITOC Inc. staff will check the compliance of all License information before resolving money refund 
issue. AITOC Inc. reserves the right to deny money refund claimed within the stated period if 
Customer's License info is incomplete and/or incorrect.<br />
    Refund requests submitted after the expiration of the 30 days period shall not be accepted.
Refunds of money charged for custom installation service shall not be issued.
AITOC Inc. considers its Product as refunded when the money has been withdrawn from its account. If 
no notification of non-acceptance has been received from client within 5 bank days, product is treated 
as refunded.<br />
    Thus client is obliged to uninstall the product, terminate all its copies and derivatives within the 5 bank 
days starting from the day of initiation of money refund process.</p>

    <p>AITOC Inc. is not responsible for any damages neither with Magento running, nor with business profits 
or information occurring due to enforced manual deleting of refunded Product or its derivatives.</p>

    <h3>10. Confidentiality</h3>
    
    <p>Each party agrees that it shall not disclose any information concerning the customers, trade secrets, 
methods, processes or procedures or any other confidential, financial or business information of the 
other party, which it learns during the course of its performance of this Agreement to any third party, 
without the prior written consent of such other party. This obligation shall survive the cancellation or 
other termination of this Agreement or License.<br />
    The Product contains trade secrets and proprietary know-how that belong to AITOC Inc. and it is being 
made available to Licensee in strict confidence. AITOC, Inc. doesn’t collect any personal or business 
information, except for the information in its Modules that ensures the Module’s valid purchase and 
exploitation, which is:
    <ul>
        <li> Server name;</li>
        <li> Server host name;</li>
        <li> Server address (IP);</li>
        <li> Magento installation version;</li>
        <li> Personal identification for the Magento installation, issued by AITOC server during purchase;</li>
        <li> Magento installation source code path;</li>
        <li> Magento default host domain name;</li>
        <li> Magento current host domain name;</li>
        <li> Module’s key name;</li>
        <li> Module’s version;</li>
        <li> Module’s identification number in AITOC DB;</li>
        <li> License purchase identification number;</li>
    </ul>
    </p>
    
    <h3>11. Disclaimer of Responsibility</h3>
    
    <p>AITOC Inc. Products are not stand-alone solutions and require Magento to be installed primarily with a 
valid Magento License.<br />
Vendor does not guarantee for its Product to operate correctly on any Magento solution, either 
modified or non-modified.<br />
ITOC Inc. does not bear any responsibility for damages or incorrect running of the Magento solution, 
occurred due to installation or utilizing of Module.<br />
AITOC Inc. disclaims all and any accountability for content of a site on which the Product is installed. 
Complaints received from any third party may result in License suspension or revocation if the matter 
cannot be resolved. License suspension action is at the sole discretion of AITOC Inc. and is intended to 
offer both parties time for settlement or advice.<br />
License reinstatement shall remain Vendor's exclusive privilege.<br />
Vendor is not liable to Customer or any third party for any damages including, but not limited to, loss 
of business or business profits, loss of business information due to using AITOC Inc. Products.<br />
By accepting this License Agreement Customer acknowledges to use the Product at own risk and has 
clear understanding of responsibility for any damage to own computer system and data.</p>

    <h3>12. Changes in Conditions</h3>
    
    <p>AITOC Inc. reserves the right to modify these agreement terms at any time. 
It is solely Customer's responsibility to inquire about any changes made to the present Agreement.</p>