<?php //echo $this->getMessagesBlock()->getGroupedHtml() ?>

<div class="inner-content customer-edit">
    <div class="block">
        <div class="inside text-box">
            <h1><?php echo $this->__('Edit Account Information') ?></h1>

            <form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate">
                <p><strong><?php echo $this->__('Customer Number'); ?>:</strong> <?php echo $this->getCustomer()->getCustomerNumber(); ?></p>

                <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>

                <label class="form-row required" for="email"><?php echo $this->__('Email Address') ?><span class="mandatory">*</span><input type="text" name="email" id="email" value="<?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="form-input-text required-entry validate-email" /></label>

                <?php echo $this->getBlockHtml('formkey')?>

                <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                <?php if ($_dob->isEnabled()): ?>
                    <li><?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?></li>
                <?php endif ?>
                <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                <?php if ($_taxvat->isEnabled()): ?>
                    <li><?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?></li>
                <?php endif ?>
                <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                <?php if ($_gender->isEnabled()): ?>
                    <li><?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?></li>
                <?php endif ?>

                <br class="clear" />

                <label class="checkbox-row-row" for="change_password"><input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> class="checkbox" /><?php echo $this->__('Change Password') ?></label>

                <br class="clear" />

                <div class="fieldset" style="display:none;">
                    <h2><?php echo $this->__('Change Password') ?></h2>

                    <label class="form-row required" for="current_password"><?php echo $this->__('Current Password') ?><span class="mandatory">*</span><input type="password" title="<?php echo $this->__('Current Password') ?>" class="form-input-text" name="current_password" id="current_password" /></label>

                    <br class="clear" />

                    <label class="form-row required" for="password"><?php echo $this->__('New Password') ?><span class="mandatory">*</span><input type="password" title="<?php echo $this->__('Current Password') ?>" class="form-input-text validate-password" name="password" id="password" /></label>
                    <label class="form-row required" for="confirmation"><?php echo $this->__('Confirm New Password') ?><span class="mandatory">*</span><input type="password" title="<?php echo $this->__('Current Password') ?>" class="form-input-text validate-cpassword" name="confirmation" id="confirmation" /></label>

                </div>


                <div class="buttons-set">
                    <p class="mandatory small-text"><?php echo $this->__('* Required Fields') ?></p>
                    <p>
                        <a class="button-link weiter-link fl" href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" title="<?php echo $this->__('Back') ?>"><span><?php echo $this->__('Back') ?></span></a>
                        <div class="fl">&nbsp;</div>
                        <div class="weiter-btn fl">
                            <input type="submit" value="" /><?php echo $this->__("Save"); ?><span></span>
                        </div>
                    </p>
                 </div>
</form>

</div></div></div>

<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function setPasswordForm(arg){
        if(arg){
            $('current_password').up(1).show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        }else{
            $('current_password').up(1).hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }
    <?php if($this->getCustomer()->getChangePassword()): ?>
        setPasswordForm(true);
    <?php endif; ?>
//]]>
</script>
