<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php
	$customerIsActive = Mage::helper('customer')->getCustomer()->getIsActive();
?>
<div class="block">
	<div class="inside">
        <h1 class="title-h3"><?php echo $this->__('Forgot Your Password?') ?></h1>

        <div class="reg-box fl">
            <div class="info-block">
				<?php if ((int) $customerIsActive === 1 || $customerIsActive === null) : ?>
                <h4><?php echo $this->__('Retrieve your password here') ?></h4>
                <p><?php echo $this->__('Please enter your email or customer number below and we will send you a new password.') ?></p>

                <form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
                    <label class="form-row"><?php echo $this->__('Customer Number') ?><input type="text" name="customer_number" alt="customer_number" id="customer_number" class="input-text form-input-text" value="" /></label>
                    <br class="clear" />
                    <label class="form-row"><?php echo $this->__('Email Address') ?><input type="text" name="email" alt="email" id="email_address" class="input-text form-input-text validate-email" value="" /></label>
                    <br class="clear" />
                    <input type="submit" class="button-link" value="<?php echo $this->__('Submit') ?>" name="send" id="send2"/>
                </form>
				<?php else: ?>
					<p>Ihr Konto ist noch nicht freigeschaltet. Bitte <a href="<?php echo Mage::getBaseUrl() . 'ueber-uns/kontakt/'; ?>">kontaktieren</a> Sie uns.</p>
				<?php endif; ?>
            </div>
        </div>
        <div class="firm-box fr">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('register_right_col')->toHtml() ?>
		</div>
    </div>
</div>


<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
