<?php /*
 * To enable the gender field in the registration form, you can follow these steps:
1. Login back-end
2. Select menu “System/Configuration”
3. Select tab “Customer Configuration”
4. Select tab “Name and Address Options”
5. Change the value of Show Gender field from “No” to “Optional” or “Required” as you want (see attachment).
 */ ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<div class="block">
	<div class="inside">
		<h1 class="title-h3"><?php echo $this->__('Register as a retailer'); ?></h1>
		<div class="reg-box fl">
			<div class="info-block">
				<?php echo $this->getChildHtml('form_fields_before')?>

                <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">

                    <?php if($this->getShowAddressFields()): ?> <!-- company address -->
                        <input type="hidden" name="create_address" value="1" />
                        <input type="hidden" name="default_billing" value="1" />
                        <input type="hidden" name="default_shipping" value="1" />

                        <span class="title-h5 dark-title"><?php echo $this->__('Address Information') ?></span>
                        <div class="reg-box-inside">
                            <label class="form-row"><?php echo $this->__('Company') ?><span class="mandatory">*</span><input type="text" class="input-text form-input-text required-entry" name="company" id="company" value="<?php echo $this->htmlEscape($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>"/></label>
                            <br class="clear" />
                            <label class="form-row"><?php echo $this->__('Street and house number') ?><span class="mandatory">*</span><input type="text" class="form-input-text input-text required-entry" name="street[]" value="<?php echo $this->htmlEscape($this->getFormData()->getStreet(0)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1"/></label>
                            <label class="form-row"><?php echo $this->__('Additional Information') ?><input type="text" class="form-input-text" name="street_additional" id="street_additional" value="<?php echo $this->htmlEscape($this->getFormData()->getStreetAdditional()) ?>"/></label>
                            <label class="form-row"><?php echo $this->__('Zip/Postal Code') ?><span class="mandatory">*</span><input type="text" name="postcode" value="<?php echo $this->htmlEscape($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text form-input-text validate-zip-international required-entry" /></label>
                            <label class="form-row"><?php echo $this->__('City') ?><span class="mandatory">*</span><input type="text" name="city" value="<?php echo $this->htmlEscape($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text form-input-text required-entry" id="city" /></label>
                            <p class="form-row">
                                <label><?php echo $this->__('Country') ?><span class="mandatory">*</span></label>
                                <?php echo $this->getCountryHtmlSelect() ?>
                            </p>
                            <p class="form-row">
                                <label><?php echo $this->__('State/Province') ?><span class="mandatory">*</span></label>
                                <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select form-input-select" style="display:none;">
                                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                </select>
                                <script type="text/javascript">
                                //<![CDATA[
                                    $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                                //]]>
                                </script>
                                <input type="text" id="region" name="region" value="<?php echo $this->htmlEscape($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none;" />
                            </p>
                        </div>

                    <?php endif; ?><!-- // company address -->



					<span class="title-h5 dark-title"><?php echo $this->__('Personal Information') ?></span>
					<div class="reg-box-inside">
                        <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->toHtml() ?>
                        <?php /* ?><p class="none-indent"><?php echo $this->__('Telephone') ?></p>
                        <label class="form-row"><?php echo $this->__('Area Code') ?><input type="text" name="telephone_area_code" id="telephone_area_code" value="<?php echo $this->htmlEscape($this->getFormData()->getTelephoneAreaCode()) ?>" title="<?php echo $this->__('Area Code') ?>" class="input-text form-input-text required-entry" /></label><?php */ ?>
                        <label class="form-row"><?php echo $this->__('Telephone') ?><span class="mandatory">*</span><input type="text" name="telephone" id="telephone" value="<?php echo $this->htmlEscape($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text form-input-text required-entry" /></label>
					</div>
					<span class="title-h5 dark-title">Wie ist die E-Mail Adresse für die Zusendung der Zugangsdaten?</span>
					<div class="reg-box-inside">
						<label class="form-row"><?php echo $this->__('Email Address') ?><span class="mandatory">*</span><input type="text" name="email" id="email_address" value="<?php echo $this->htmlEscape($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text form-input-text validate-email required-entry" /></label>
						<label class="form-row"><?php echo $this->__('Confirm Email Address') ?><span class="mandatory">*</span><input type="text" name="confirm_email" id="confirm_email_address" value="<?php echo $this->htmlEscape($this->getFormData()->getConfirmEmail()) ?>" title="<?php echo $this->__('Confirm Email Address') ?>" class="input-text form-input-text validate-email required-entry" /></label>
					</div>
					<span class="title-h5 dark-title"><?php echo $this->__("Do you have any questions or additional information?"); ?></span>
					<div class="reg-box-inside">
						<label><?php echo $this->__("Your message"); ?></label>
						<textarea name="customer_message" id="customer_message"><?php echo $this->htmlEscape($this->getFormData()->getCustomerMessage()) ?></textarea>
					</div>
					<a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="link-prev2 fl"><?php echo $this->__("back"); ?></a>
					<div class="weiter-btn fr">
                        <input type="submit" value="" onclick="return dataForm.submit();"/><?php echo $this->__("Continue registration"); ?><span></span>
                    </div>
				</form>
			</div>
		</div>
        <div class="firm-box fr">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('register_right_col')->toHtml() ?>
		</div>

	</div>
</div>

<script type="text/javascript">
    //<![CDATA[
        $j("#content").addClass("register-page").addClass("reg-steps");
        $j("#country").addClass("form-input-select");

        var dataForm = new VarienForm('form-validate', true);

        <?php if($this->getShowAddressFields()): ?>
            new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
    //]]>
</script>


<?php /* ************************* ?>
<div class="account-create">
    <div class="page-title">
        <h1><?php echo $this->__('Create an Account') ?></h1>
    </div>
    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
        <div class="fieldset">
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <h2 class="legend"><?php echo $this->__('Personal Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->toHtml() ?>
                </li>
                <li>
                    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="email" id="email_address" value="<?php echo $this->htmlEscape($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                    </div>
                </li>
                <?php if ($this->isNewsletterEnabled()): ?>
                <li class="control">
                    <div class="input-box">
                        <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                    </div>
                    <label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
                </li>
                <?php endif ?>
            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
            <?php if ($_dob->isEnabled()): ?>
                <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
            <?php endif ?>
            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
            <?php endif ?>
            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($_gender->isEnabled()): ?>
                <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
            <?php endif ?>
            </ul>
        </div>
    <?php if($this->getShowAddressFields()): ?>
        <div class="fieldset">
            <input type="hidden" name="create_address" value="1" />
            <h2 class="legend"><?php echo $this->__('Address Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="company"><?php echo $this->__('Company') ?></label>
                        <div class="input-box">
                            <input type="text" name="company" id="company" value="<?php echo $this->htmlEscape($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                        <div class="input-box">
                            <input type="text" name="telephone" id="telephone" value="<?php echo $this->htmlEscape($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text required-entry" />
                        </div>
                    </div>
                </li>
                <li class="wide">
                    <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->htmlEscape($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text required-entry" />
                    </div>
                </li>
            <?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
                <li class="wide">
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->htmlEscape($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i?>" class="input-text" />
                    </div>
                </li>
            <?php endfor ?>
                <li class="fields">
                    <div class="field">
                        <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                        <div class="input-box">
                            <input type="text" name="city" value="<?php echo $this->htmlEscape($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text required-entry" id="city" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                        <div class="input-box">
                            <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                            //<![CDATA[
                                $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                            //]]>
                            </script>
                            <input type="text" id="region" name="region" value="<?php echo $this->htmlEscape($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none;" />
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                        <div class="input-box">
                            <input type="text" name="postcode" value="<?php echo $this->htmlEscape($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international required-entry" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                        <div class="input-box">
                            <?php echo $this->getCountryHtmlSelect() ?>
                        </div>
                    </div>
                </li>
            </ul>
            <input type="hidden" name="default_billing" value="1" />
            <input type="hidden" name="default_shipping" value="1" />
        </div>
    <?php endif; ?>
        <div class="fieldset">
            <h2 class="legend"><?php echo $this->__('Login Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <div class="buttons-set">
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
            <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
    //]]>
    </script>
</div>

<?php ************** */ ?>
