<?php if ($this->displayBoth()):?>
<dt><?php echo $this->helper('tax')->__('Subtotal (Excl. Tax)') ?>:</dt>
<dd><?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValueExclTax()) ?></dd>
<dt><?php echo $this->helper('tax')->__('Subtotal (Incl. Tax)') ?>:</dt>
<dd><?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValueInclTax()) ?></dd>
<?php else : ?>
<dt><?php echo $this->getTotal()->getTitle() ?>:</dt>
<dd><?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?></dd>
<?php endif;?>
