<form id="co-billing-form" action="">
    <div class="note-block fr">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('checkout_infoblock_shipping')->toHtml(); ?>
    </div>

    <div class="form-block">
        <div class="addressHtml">
                   <?php echo $this->getAddress()->format('html'); ?>
               </div>
<?php /* ?>
        <?php if ($this->customerHasAddresses()): ?>
           <label class="checkout-address-select">
               <?php //echo $this->__('Select a billing address from your address book or enter a new address.') ?>
               <?php //echo $this->getAddressesHtmlSelect('billing') ?>

           </label>
        <?php endif ?><?php */ ?>

        <div id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?> class="checkout-forms">
            <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id" />

            <label class="form-row" for="billing:company"><?php echo $this->__('Company') ?><input type="text" id="billing:company" name="billing[company]" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text form-input-text" /></label>

            <br class="clear" />

            <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress()->getFirstname() ? $this->getAddress() : $this->getQuote()->getCustomer())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>

            <label class="form-row required" for="billing:street1"><?php echo $this->__('Street and house number') ?><span class="mandatory">*</span><input type="text" title="<?php echo $this->__('Street and house number') ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="input-text form-input-text required-entry" /></label>
            <label class="form-row" for="billing:street_additional"><?php echo $this->__('Additional Information') ?><input type="text" title="<?php echo $this->__('Additional Information') ?>" name="billing[street_additional]" id="billing:street_additional" value="<?php echo $this->htmlEscape($this->getAddress()->getStreetAdditional()) ?>" class="input-text form-input-text" /></label>


            <div class="form-row">
                <label for="billing:postcode" class="required"><?php echo $this->__('Zip/Postal Code') ?><span class="mandatory">*</span><input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" class="input-text form-input-text wt40 validate-zip-international required-entry" /></label>
                <label for="billing:city" class="required"><?php echo $this->__('City') ?><span class="mandatory">*</span><input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" class="input-text required-entry form-input-text wt85" id="billing:city" /></label>
            </div>
            <label for="billing:telephone" class="form-row required"><?php echo $this->__('Telephone') ?><span class="mandatory">*</span><input type="text" name="billing[telephone]" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text form-input-text required-entry" id="billing:telephone" /></label>

            <p class="form-row shipping_selects">
                <label class="required" for="billing:country_id"><?php echo $this->__('Country') ?><span class="mandatory">*</span></label>
                <?php echo $this->getCountryHtmlSelect('billing') ?>
            </p>

            <p class="form-row shipping_selects">
                <label class="required" for="billing:region"><?php echo $this->__('State/Province') ?><span class="mandatory">*</span></label>
                <select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select billing_region_id" style="display:none;">
                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                </select>

                <script type="text/javascript">
                //<![CDATA[
                    $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                //]]>
                </script>
                <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text form-input-text" style="display:none;" />
            </p>


            <br class="clear" />

            <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
            <p><input type="checkbox" name="billing[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="billing:save_in_address_book" onchange="if(window.shipping) shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox fl" /><label for="billing:save_in_address_book"><?php echo $this->__('Save in address book') ?></label></p>
            <?php else:?>
                <input type="hidden" name="billing[save_in_address_book]" value="1" />
            <?php endif;?>

            <?php if (!$this->canShip()): ?>
                <input type="hidden" name="billing[use_for_shipping]" value="1" />
            <?php endif; ?>

         </div>


        <?php if ($this->canShip()): ?>
            <input type="hidden" name="billing[use_for_shipping]" value="1" />

            <?php /* ?>

            <br class="clear" />
            <p><input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1"<?php if ($this->isUseBillingAddressForShipping()) {?> checked="checked"<?php }?> title="<?php echo  $this->__('Ship to this address') ?>" onclick="$('shipping:same_as_billing').checked = true;" class="radio fl" /><label for="billing:use_for_shipping_yes"><?php echo  $this->__('Ship to this address') ?></label></p>
            <br class="clear" />
            <p><input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_no" value="0"<?php if (!$this->isUseBillingAddressForShipping()) {?> checked="checked"<?php }?> title="<?php echo $this->__('Ship to different address') ?>" onclick="$('shipping:same_as_billing').checked = false;" class="radio fl" /><label for="billing:use_for_shipping_no"><?php echo $this->__('Ship to different address') ?></p>

            <?php */ ?>

        <?php endif; ?>
<?php /* ?>
        <br class="clear" />
         <p class="mandatory small-text"><?php echo $this->__('* Required Fields') ?></p>
<?php */ ?>

    </div>

    <br class="clear" />

    <div class="buttons-set" id="billing-buttons-container">
       <!-- <p>
            <a class="weiter-btn fr" href="#" onclick="billing.save(); return false;" title="<?php /*echo $this->__('Continue') */?>"><?php /*echo $this->__('Continue') */?><span></span></a>
        </p>-->

        <span id="billing-please-wait" class="please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>


</form>
<script type="text/javascript">
//<![CDATA[
    var billing = new Billing('co-billing-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveBilling') ?>');
    var billingForm = new VarienForm('co-billing-form');

    //billingForm.setElementsRelation('billing:country_id', 'billing:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');
    $('billing-address-select') && billing.newAddress(!$('billing-address-select').value);

    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', countryRegions, undefined, 'billing:postcode');
//]]>
</script>
