<form action="" id="co-shipping-form">
    <div class="note-block fl">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('checkout_infoblock_shipping')->toHtml(); ?>
    </div>

    <div class="form-block">
        <?php if ($this->customerHasAddresses()): ?>
           <label class="checkout-address-select">
               <?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?>
               <?php echo $this->getAddressesHtmlSelect('shipping') ?>
           </label>
        <?php endif ?>
            <div id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?> class="checkout-forms">
                <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />

                <label class="form-row" for="shipping:company"><?php echo $this->__('Company') ?><input type="text" id="shipping:company" name="shipping[company]" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text form-input-text" onchange="shipping.setSameAsBilling(false);" /></label>

                <br class="clear" />

                <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')->toHtml() ?>

                <label class="form-row required" for="shipping:street1"><?php echo $this->__('Street and house number') ?><span class="mandatory">*</span><input type="text" title="<?php echo $this->__('Street and house number') ?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="input-text form-input-text required-entry" onchange="shipping.setSameAsBilling(false);" /></label>
                <label class="form-row" for="shipping:street_additional"><?php echo $this->__('Additional Information') ?><input type="text" title="<?php echo $this->__('Additional Information') ?>" name="shipping[street_additional]" id="shipping:street_additional" value="<?php echo $this->htmlEscape($this->getAddress()->getStreetAdditional()) ?>" class="input-text form-input-text" onchange="shipping.setSameAsBilling(false);" /></label>

                <div class="form-row">
                    <label for="shipping:postcode" class="required"><?php echo $this->__('Zip/Postal Code') ?><span class="mandatory">*</span><input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" class="input-text form-input-text wt40 validate-zip-international required-entry" onchange="shipping.setSameAsBilling(false);" /></label>
                    <label for="shipping:city" class="required"><?php echo $this->__('City') ?><span class="mandatory">*</span><input type="text" title="<?php echo $this->__('City') ?>" name="shipping[city]" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" class="input-text required-entry form-input-text wt85" id="shipping:city" onchange="shipping.setSameAsBilling(false);" /></label>
                </div>
                <label for="shipping:telephone" class="form-row required"><?php echo $this->__('Telephone') ?><span class="mandatory">*</span><input type="text" name="shipping[telephone]" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text form-input-text required-entry" id="shipping:telephone" onchange="shipping.setSameAsBilling(false);" /></label>

                <p class="form-row shipping_selects">
                    <label class="required" for="shipping:country_id"><?php echo $this->__('Country') ?><span class="mandatory">*</span></label>
                    <?php echo $this->getCountryHtmlSelect('shipping') ?>
                </p>

                <p class="form-row shipping_selects">
                    <label class="required" for="shipping:region"><?php echo $this->__('State/Province') ?><span class="mandatory">*</span></label>
                    <select id="shipping:region_id" name="shipping[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select shipping_region_id" style="display:none;">
                        <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                    </select>

                    <script type="text/javascript">
                    //<![CDATA[
                        $('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                    //]]>
                    </script>
                    <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text form-input-text" style="display:none;" />
                </p>

                <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                    <br class="clear" />
                    <p><input type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="shipping:save_in_address_book" onchange="shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox fl" /><label for="shipping:save_in_address_book"><?php echo $this->__('Save in address book') ?></label></p>
                <?php else:?>
                    <input type="hidden" name="shipping[save_in_address_book]" value="1" />
                <?php endif;?>

                <br class="clear" />

            </div>
             <p><input type="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1"<?php if($this->getAddress()->getSameAsBilling()): ?> checked="checked"<?php endif; ?> title="<?php echo $this->__('Use Billing Address') ?>" onclick="shipping.setSameAsBilling(this.checked)" class="checkbox fl" /><label for="shipping:same_as_billing"><?php echo $this->__('Use Billing Address') ?></label></p>

        <br class="clear" />
        <p class="mandatory small-text"><?php echo $this->__('* Required Fields') ?></p>
    </div>

    <br class="clear" />



    <div class="buttons-set" id="shipping-buttons-container">


        <p>
            <a class="button-link weiter-link fl" href="#" onclick="checkout.back(); return false;" title="<?php echo $this->__('Back') ?>"><span><?php echo $this->__('Back') ?></span></a>
            <div class="fl">&nbsp;</div>
            <a class="weiter-btn fr" href="#" onclick="shipping.save(); return false;" title="<?php echo $this->__('Continue') ?>"><?php echo $this->__('Continue') ?><span></span></a>
        </p>
        
        <span id="shipping-please-wait" class="please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var shipping = new Shipping('co-shipping-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveShipping') ?>',
        '<?php echo $this->getUrl('checkout/onepage/shippingMethod') ?>');
    var shippingForm = new VarienForm('co-shipping-form');
    shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
    //shippingForm.setElementsRelation('shipping:country_id', 'shipping:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');
    $('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);

    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', countryRegions, undefined, 'shipping:postcode');
//]]>
</script>
