<?php $_item = $this->getItem() ?>
<?php $_itemOptions = $_item->getProductOptions(); ?>
<?php $_cpId = $_itemOptions['info_buyRequest']['cpid']; ?>
<?php $_product = Mage::getModel('catalog/product')->setStoreId($_item->getOrder()->getStoreId())->load($_cpId); ?>

<tr class="border <?php echo $_item->getIsOddDisplay() ? 'odd' : 'even'; ?>">
    <td><img src="<?php echo Mage::helper('catalog/image')->init($_product, 'thumbnail')->resize(57); ?>" width="57" height="57"/></td>
    <td>
        <h4 class="product-name"><?php echo $this->htmlEscape($_item->getName()) ?></h4>

        <?php if($_options = $this->getItemOptions()): ?>
            <dl class="item-options">
            <?php foreach ($_options as $_option) : ?>
                <dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
                <?php if (!$this->getPrintStatus()): ?>
                    <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                    <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>>
                        <?php echo $_formatedOptionValue['value'] ?>
                        <?php if (isset($_formatedOptionValue['full_view'])): ?>
                        <div class="truncated_full_value">
                            <dl class="item-options">
                                <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                                <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                            </dl>
                        </div>
                        <?php endif; ?>
                    </dd>
                <?php else: ?>
                    <dd>
                        <?php echo nl2br($this->htmlEscape( (isset($_option['print_value']) ? $_option['print_value'] : $_option['value']) )) ?>
                    </dd>
                <?php endif; ?>
            <?php endforeach; ?>
            </dl>
        <?php endif; ?>
    </td>

    <td class="align-center"><?php echo $this->htmlEscape(Mage::helper('core/string')->splitInjection($this->getSku())) ?></td>

    <td class="align-center">
        <span class="cart-price">
            <?php echo $this->getOrder()->formatPrice($this->getItem()->getPrice()) ?>
        </span>
    </td>

    <td class="align-center">
        <span class="nobr">
                <?php if ($this->getItem()->getQtyOrdered() > 0): ?>
            <?php echo $this->__('Ordered'); ?>: <strong><?php echo $this->getItem()->getQtyOrdered()*1 ?></strong><br />
        <?php endif; ?>
        <?php if ($this->getItem()->getQtyShipped() > 0): ?>
            <?php echo $this->__('Shipped'); ?>: <strong><?php echo $this->getItem()->getQtyShipped()*1 ?></strong><br />
        <?php endif; ?>
        <?php if ($this->getItem()->getQtyCanceled() > 0): ?>
            <?php echo $this->__('Canceled'); ?>: <strong><?php echo $this->getItem()->getQtyCanceled()*1 ?></strong><br />
        <?php endif; ?>
        <?php if ($this->getItem()->getQtyRefunded() > 0): ?>
            <?php echo $this->__('Refunded'); ?>: <strong><?php echo $this->getItem()->getQtyRefunded()*1 ?></strong><br />
        <?php endif; ?>
        </span>
    </td>

    <td class="align-center">
        <span class="cart-price">
            <?php echo $this->getOrder()->formatPrice($this->getItem()->getRowTotal()) ?>
        </span>
    </td>
</tr>
