<div class="inner-content">

    <div class="block">
        <div class="inside">
            <h1><?php echo $this->__('Checkout') ?></h1>

            <script type="text/javascript" src="<?php echo $this->getJsUrl('varien/accordion.js') ?>"></script>
            <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/opcheckout.js') ?>"></script>
            <script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>

            <ol class="opc" id="checkoutSteps">
                <?php $i=0; foreach($this->getSteps() as $_stepId => $_stepInfo): ?>
                    <?php if (!$this->getChild($_stepId) || !$this->getChild($_stepId)->isShow()): continue; endif; $i++; $blockColor = ($i%2 != 0 ? 'green' : 'yellow'); ?>
                    <li id="opc-<?php echo $_stepId ?>" class="section<?php echo !empty($_stepInfo['allow'])?' allow':'' ?><?php echo !empty($_stepInfo['complete'])?' saved':'' ?>">
                       <div class="info-block-<?php echo $blockColor; ?> step-title">
                            <!-- <span class="stepNo"><?php echo $this->__('Step') . ' ' . $i; ?></span> -->
                            <span class="dark-title title-h5 align-center"><?php echo $_stepInfo['label'] ?></span>
                            <!-- <a href="#"><?php echo $this->__('Edit') ?></a> -->
                       </div>

                        <div id="checkout-step-<?php echo $_stepId ?>" class="step a-item info-block-<?php echo $blockColor; ?> clearfix" style="">
							<?php if ( $i == 1 ) : ?>
								<?php echo $this->getChildHtml($_stepId) ?>
							<?php else : ?>
								<?php echo $this->getChildHtml('onepage_stephelper'); ?>
							<?php endif; ?>
                        </div>
                    </li>
                <?php endforeach ?>
                
            </ol>
        </div>
    </div>
</div>



<script type="text/javascript">
//<![CDATA[
    $j("#content").addClass("cart-checkout");

    var accordion = new Accordion('checkoutSteps', '.step-title', true);
    <?php if($this->getActiveStep()): ?>
    accordion.openSection('opc-<?php echo $this->getActiveStep() ?>');
    <?php endif ?>
    var checkout = new Checkout(accordion,{
        progress: '<?php echo $this->getUrl('checkout/onepage/progress') ?>',
        review: '<?php echo $this->getUrl('checkout/onepage/review') ?>',
        saveMethod: '<?php echo $this->getUrl('checkout/onepage/saveMethod') ?>',
        failure: '<?php echo $this->getUrl('checkout/cart') ?>'}
    );
//]]>
</script>