<?php /*  ***************** ?>
<div class="toolbar">
    <div class="pager">
        <p class="amount">
            <?php if($this->getLastPageNum()>1): ?>
                <?php echo $this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
            <?php else: ?>
                <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
            <?php endif; ?>
        </p>

        <div class="limiter">
            <label><?php echo $this->__('Show') ?></label>
            <select onchange="setLocation(this.value)">
            <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                    <?php echo $_limit ?>
                </option>
            <?php endforeach; ?>
            </select> <?php echo $this->__('per page') ?>
        </div>

        <?php echo $this->getPagerHtml() ?>

    </div>

    <?php if( $this->isExpanded() ): ?>
    <div class="sorter">
        <?php if( $this->isEnabledViewSwitcher() ): ?>
        <p class="view-mode">
            <?php $_modes = $this->getModes(); ?>
            <?php if($_modes && count($_modes)>1): ?>
            <label><?php echo $this->__('View as') ?>:</label>
            <?php foreach ($this->getModes() as $_code=>$_label): ?>
                <?php if($this->isModeActive($_code)): ?>
                    <strong title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></strong>&nbsp;
                <?php else: ?>
                    <a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></a>&nbsp;
                <?php endif; ?>
            <?php endforeach; ?>
            <?php endif; ?>
        </p>
        <?php endif; ?>

        <div class="sort-by">
            <label><?php echo $this->__('Sort By') ?></label>
            <select onchange="setLocation(this.value)">
            <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                <option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                    <?php echo $this->__($_order) ?>
                </option>
            <?php endforeach; ?>
            </select>
            <?php if($this->getCurrentDirection() == 'desc'): ?>
                <a href="<?php echo $this->getOrderUrl(null, 'asc') ?>" title="<?php echo $this->__('Set Ascending Direction') ?>"><img src="<?php echo $this->getSkinUrl('images/i_desc_arrow.gif') ?>" alt="<?php echo $this->__('Set Ascending Direction') ?>" class="v-middle" /></a>
            <?php else: ?>
                <a href="<?php echo $this->getOrderUrl(null, 'desc') ?>" title="<?php echo $this->__('Set Descending Direction') ?>"><img src="<?php echo $this->getSkinUrl('images/i_asc_arrow.gif') ?>" alt="<?php echo $this->__('Set Descending Direction') ?>" class="v-middle" /></a>
            <?php endif; ?>
        </div>
    </div>
    <?php endif; ?>
</div>
<?php */ ?>



<div id="sub-cat-nav">
<?php if ($this->getPlacement() == 'top') : ?>
    <?php echo $this->getChildHtml('materialnav'); // filter by material ?>

    <?php if($this->getCollection()->getSize()): ?>
        <div class="sort">
            <p><?php echo $this->__('Sort by'); ?></p>
            <select onchange="setLocation(this.value)" id="sort">
            <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                <?php if ($_key == 'position') continue; ?>
                <option class="price-up" value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key) && $this->getCurrentDirection() == 'asc'): ?> selected="selected"<?php endif; ?>>
                    <?php if ($this->__($_order) == 'Name') : ?>
                      <?php echo 'Name A-Z' ?>   
                    <?php else : ?>
                    <?php echo $this->__($_order) ?> <?php echo $this->__('up') ?>
                    <?php endif; ?>                    
                </option>
                <option class="price-down" value="<?php echo $this->getOrderUrl($_key, 'desc') ?>"<?php if($this->isOrderCurrent($_key) && $this->getCurrentDirection() == 'desc'): ?> selected="selected"<?php endif; ?>>
                    <?php if ($this->__($_order) == 'Name') : ?>
                      <?php echo 'Name Z-A' ?>  
                    <?php else : ?>
                      <?php echo $this->__($_order) ?> <?php echo $this->__('down') ?>
                    <?php endif; ?>
                </option>                
            <?php endforeach; ?>
            </select>            
        </div>

        <div class="items-page">
            <p><?php echo $this->__('Items') ?> <?php echo $this->__('per page') ?></p>
            <ul>
                <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                    <li<?php if($this->isLimitCurrent($_key)): ?> class="current"<?php endif ?>><a href="<?php echo $this->getLimitUrl($_key) ?>"><?php echo $_limit ?></a></li>
                <?php endforeach; ?>
            </ul>
        </div>
	<?php endif ?>
<?php else : ?>
	<?php if($this->getCollection()->getSize()): ?>
        <?php  echo $this->getPagerHtml() ?>
	<?php endif ?>
<?php endif ?>

</div>

