<?php if ($this->showPrefix()): ?>
    <p class="form-row">
        <label><?php echo $this->__('Prefix') ?><span class="mandatory">*</span></label>
        <?php if ($this->getPrefixOptions()===false): ?>
            <input type="text" id="<?php echo $this->getFieldId('prefix')?>" name="<?php echo $this->getFieldName('prefix')?>" value="<?php echo $this->htmlEscape($this->getObject()->getPrefix()) ?>" title="<?php echo $this->__('Prefix') ?>" class="input-text form-input-text<?php if ($this->isPrefixRequired()):?> required-entry<?php endif; ?>" <?php echo $this->getFieldParams() ?> />
        <?php else: ?>
            <select id="<?php echo $this->getFieldId('prefix')?>" name="<?php echo $this->getFieldName('prefix')?>" title="<?php echo $this->__('Prefix') ?>"<?php if ($this->isPrefixRequired()):?> class="required-entry"<?php endif; ?> <?php echo $this->getFieldParams() ?>>

            <?php $prefixOptions = $this->getPrefixOptions(); ksort($prefixOptions); ?>
            <?php foreach ($prefixOptions as $_option): ?>
                <option value="<?php echo $_option?>"<?php if ($this->getObject()->getPrefix()==$_option):?> selected="selected"<?php endif; ?>><?php echo $this->__($_option)?></option>
            <?php endforeach ?>
            </select>
        <?php endif; ?>
    </p>
    <br class="clear" />
<?php endif; ?>
<label class="form-row"><?php echo $this->__('First Name') ?><span class="mandatory">*</span><input type="text" id="<?php echo $this->getFieldId('firstname')?>" name="<?php echo $this->getFieldName('firstname')?>" value="<?php echo $this->htmlEscape($this->getObject()->getFirstname()) ?>" title="<?php echo $this->__('First Name') ?>" class="input-text form-input-text required-entry" <?php echo $this->getFieldParams() ?> /></label>
<label class="form-row"><?php echo $this->__('Last Name')  ?><span class="mandatory">*</span><input type="text" id="<?php echo $this->getFieldId('lastname')?>" name="<?php echo $this->getFieldName('lastname')?>" value="<?php echo $this->htmlEscape($this->getObject()->getLastname()) ?>" title="<?php echo $this->__('Last Name') ?>" class="input-text form-input-text required-entry" <?php echo $this->getFieldParams() ?> /></label>
<br class="clear" />