<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="block">
	<div class="inside text-box">
		<div class="w445 fl">
			<h1 class="title-h3"><?php echo $this->__('Thank you for registering!'); ?></h1>
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('register_success_message_left')->toHtml() ?>
			<a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>" class="button-link">Zur Startseite</a>
    	</div>
		<div class="block w445 fr">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('register_success_message_right')->toHtml() ?>
    	</div>
	</div>
</div>