<div class="qOrderWindow"><div class="qOrderWindowIn">
    
    <div class='qSearchInputWrap'>
        <input type="text" class="qSearchByArticul" />
        <input type="button" class="qStartSearch" value="Search" />
        <div class="qLoader"><img src="<?php echo Mage::getBaseUrl("js") ?>/magenmagic/quickorder/img/loader.gif" alt=""></div>
    </div>

    <form action="<?php echo Mage::getUrl('quickorder/index/addToCart'); ?>">
        <table class="qTable" style="display: none">
            <thead>
                <tr>
                    <th class='qSkuTd'><?php echo $this->__('SKU'); ?></th>
                    <th class='productColumn'><?php echo $this->__('Product'); ?></th>
                    <th><?php echo $this->__('Remove'); ?></th>
                    <th><?php echo $this->__('Status'); ?></th>
                    <th><?php echo $this->__('Quantity'); ?></th>
                    <th><?php echo $this->__('Price'); ?></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
        <input class="qToCart" type="submit" value="<?php echo $this->__('Add To Cart'); ?>" />
    </form>
</div></div>