<?php if ( $this->getTotalNum() > 0) :?>
<div class="toolbar">
    <div class="pager">
        <p class="amount">
            <span><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></span>
		</p>
	    <div class="pages">
	        <ol>
	        <?php if ($this->getBackItemUrl()): ?>
	            <li >
					<a class="previous i-back" href="<?php echo $this->getBackItemUrl() ?>" title="<?php echo $this->getBackItemTitle() ?>">
						<img 	src="<?php echo $this->getSkinUrl('images/spacer.gif') ?>" alt="<?php echo $this->__('Back') ?>"/>
		            </a>
	            </li>
	        <?php endif;?>
	        <?php if (!$this->isFirstItem()): ?>
	            <li >
					<a class="previous i-first" href="<?php echo $this->getFirstItemUrl() ?>" title="<?php echo $this->getFirstItemTitle() ?>">
						<img 	src="<?php echo $this->getSkinUrl('images/spacer.gif') ?>" alt="<?php echo $this->__('First') ?>"/>
		            </a>
	            </li>
	            <li >
	                <a class="previous i-previous" href="<?php echo $this->getPreviousItemUrl() ?>" title="<?php echo $this->getPreviousItemTitle() ?>">
                    	<img 	src="<?php echo $this->getSkinUrl('images/spacer.gif') ?>" alt="<?php echo $this->__('Previous') ?>"/>
	                </a>
	            </li>
	        <?php endif;?>
	        <?php foreach ($this->getFrameItems() as $_item): ?>
	            <?php if ($this->isItemCurrent($_item)): ?>
	                <li class="current"><?php echo $_item?></li>
	            <?php else: ?>
	                <li ><a href="<?php echo $this->getItemUrl($_item) ?>" title="<?php echo $this->getItemTitle($_item)?>"><?php echo $_item ?></a></li>
	            <?php endif;?>
	        <?php endforeach;?>
	        <?php if (!$this->isLastItem()): ?>
	            <li>
	                <a class="next i-next" href="<?php echo $this->getNextItemUrl() ?>" title="<?php echo $this->getNextItemTitle() ?>">
                    	<img 	src="<?php echo $this->getSkinUrl('images/spacer.gif') ?>" alt="<?php echo $this->__('Next') ?>"/>
	                </a>
	            </li>
	            <li >
					<a class="previous i-last" href="<?php echo $this->getLastItemUrl() ?>" title="<?php echo $this->getLastItemTitle() ?>">
						<img 	src="<?php echo $this->getSkinUrl('images/spacer.gif') ?>" alt="<?php echo $this->__('Last') ?>"/>
		            </a>
	            </li>
	        <?php endif;?>
	        </ol>
	    </div>
    </div>
    <div class="clear"></div>
</div>
<?php endif; ?>
