<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<div class="inner-content">

    <div class="block">
        <div class="inside">

        <h1><?php echo $this->__('Share Your Wishlist') ?></h1>


<form action="<?php echo $this->getSendUrl() ?>" id="form-validate" method="post">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo $this->__('Sharing Information') ?></h2>

        <div>
            <label class="form-row"><?php echo $this->__('Email addresses, separated by commas') ?><textarea name="emails" cols="60" rows="5" id="email_address" class="validate-emails required-entry"><?php echo $this->getEnteredData('emails') ?></textarea></label>
            <br class="clear" />
            <label class="form-row"><?php echo $this->__('Message') ?><textarea id="message" name="message" cols="60" rows="5"><?php echo $this->getEnteredData('message') ?></textarea></label>
        </div>

        <br class="clear" />

        <div>
             <a class="button-link weiter-link" href="<?php echo $this->getUrl('*/')?>"><span><?php echo $this->__('Back')?></span></a>
            <input type="submit" class="button-link" value="<?php echo $this->__('Share Wishlist') ?>" />
        </div>


    </div>
</form>

</div></div></div>
    
<script type="text/javascript">
//<![CDATA[
Validation.addAllThese([
    ['validate-emails', '<?php echo $this->__('Please enter a valid email addresses, separated by commas. For example johndoe@domain.com, johnsmith@domain.com.') ?>', function (v) {
    if(Validation.get('IsEmpty').test(v)) {
        return true;
    }

    var valid_regexp = /^[a-z0-9\._-]{1,30}@([a-z0-9_-]{1,30}\.){1,5}[a-z]{2,4}$/i;
    var emails = v.split(',');

    for (var i=0; i<emails.length; i++) {
        if(!valid_regexp.test(emails[i].strip())) {
            return false;
        }
    }

    return true;
    }]
]);
var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
