<?php $_orders = $this->getOrders(); ?>
<div class="inner-content">
    <div class="block">
        <div class="inside">
            <h1><?php echo $this->__('My Orders') ?></h1>

            <div class="page-nav"><?php echo $this->getPagerHtml(); ?></div>
            <?php if($_orders->getSize()): ?>

                <table class="cart-table order-table">
                    <thead>
                    <tr>
                        <td><?php echo $this->__('Order #'); ?></td>
                        <td><?php echo $this->__('Date'); ?></td>
                        <td><?php echo $this->__('Ship To'); ?></td>
                        <td class="align-center"><?php echo $this->__('Order Total'); ?></td>
                        <td>&nbsp;</td>
                    </tr>
                    </thead>
                    <tr>
                        <td colspan="6" class="thead-ind">&nbsp;</td>
                    </tr>
                    <?php $cntr = 0; foreach ($_orders as $_order): ?>
                        <tr <?php if ($cntr++%2 == 0) : ?>class="even"<?php endif; ?>>
                            <td><?php echo $_order->getRealOrderId() ?></td>
                            <td><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
                            <td><?php echo $_order->getShippingAddress() ? $this->htmlEscape($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                            <td class="align-center"><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                            <td  lass="align-center">
                                            <span class="nobr"><a href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $this->__('View Order') ?></a>
                                                <?php /*<span class="separator">|</span><a href="<?php echo $this->getTrackUrl($_order) ?>"><?php echo $this->__('Track Order') ?></a>&nbsp;*/ ?>
                                                <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                                                <span class="separator">|</span> <a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-reorder"><?php echo $this->__('Reorder') ?></a>
                                            <?php endif ?>
                                            </span>
                                        </td>

                        </tr>
                    <?php endforeach; ?>

                </table>

            <div class="page-nav"><?php echo $this->getPagerHtml(); ?></div>



            <?php else : ?>
                <p><?php echo $this->__('You have placed no orders.') ?></p>
            <?php endif; ?>
        </div>
    </div>
</div>

