            <?php $_order = $this->getOrder() ?>

            <h2 class="table-caption"><?php echo $this->__('Items Ordered') ?>
                <?php if ($_order->getTracksCollection()->count()) : ?>
                    <span class="separator">|</span> <a href="#" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_order) ?>','trackorder','top=0,left=0,width=800,height=600,resizable=yes,scrollbars=yes'); return false;" title="<?php echo $this->__('Track your order') ?>"><?php echo $this->__('Track your order') ?></a>
                <?php endif; ?>
            </h2>

            <?php echo $this->getChildHtml('order_items') ?>

            <?php $_history = $this->getOrder()->getVisibleStatusHistory() ?>

            <?php if (count($_history)): ?>
                <div class="info-block-t">
                    <h2 class="sub-title"><?php echo $this->__('About Your Order') ?></h2>
                    <dl class="order-about">
                        <?php foreach ($_history as $_historyItem): ?>
                            <dt><?php echo $this->formatDate($_historyItem->getCreatedAtStoreDate(), 'medium', true) ?></dt>
                            <dd><?php echo $this->escapeHtml($_historyItem->getComment()) ?></dd>
                        <?php endforeach; ?>
                    </dl>
                </div>
            <?php endif; ?>

            <div class="buttons-set">
                <a class="button-link weiter-link fl" href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" title="<?php echo $this->__('Back to My Orders') ?>"><span><?php echo $this->__('Back to My Orders') ?></span></a>
            </div>




        </div>
    </div>
</div>
