<?php //echo $this->getMessagesBlock()->getGroupedHtml() ?>

<div class="inner-content">
    <div class="dashboard block">
        <div class="inside text-box">
            <h1><?php echo $this->__('My Dashboard') ?></h1>
            <?php echo $this->getChildHtml('hello') ?>
            <?php //echo $this->getChildHtml('top') ?>
            <div class="box-account box-info">
                <div class="box-head">
                    <h2><?php echo $this->__('Account Information') ?></h2>
                </div>
                <?php echo $this->getChildHtml('info') ?>
                <?php //echo $this->getChildHtml('address') ?>
            </div>
            <?php //echo $this->getChildHtml('info1') ?>
            <?php //echo $this->getChildHtml('info2') ?>
        </div>
    </div>
</div>
