<?php

/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Autorelated
 * @copyright  Copyright (c) 2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<?php

/*
  public function showNativeBlock(){
  return ;
  }

  public function iterateBlock(){
  Mage::getSingleton('awautorelated/blocks_product')->iterateBlock();
  }

  public function markAsShowed(){
  Mage::getSingleton('awautorelated/blocks_product')->markAsShowed();
  }
 */
?>
<?php

if (Mage::getSingleton('awautorelated/blocks_product')->showNativeBlock())
    echo $this->getChildHtml('catalog-product-related');
?>
