<dl class="cart-sum">
    <?php echo $this->renderTotals(); ?>
    <?php echo $this->renderTotals('footer'); ?>
<!--	<dt>Summe netto:</dt><dd>300,00€</dd>
	<dt>Versandkosten:</dt><dd>7,50€</dd>
	<dt>19% USt.</dt><dd>58,00€</dd>
	<dt class="gesamt">Gesamt brutto</dt><dd class="gesamt">400,00€</dd>
	-->
</dl>
<?php /* ************************* ?>
<table id="shopping-cart-totals-table">
    <col />
    <col width="1" />
    <tfoot>
        <?php echo $this->renderTotals('footer'); ?>
    </tfoot>
    <tbody>
        <?php echo $this->renderTotals(); ?>
    </tbody>
</table>
<?php ****************************** */ ?>