<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $topCategory = Mage::helper('jewellery')->getTopCategory();
    $currentCategory = Mage::registry("current_category") ? Mage::registry("current_category") : $topCategory;

    $isLoggedIn = Mage::helper('customer')->isLoggedIn();

?>

<div class="section-title">
    <?php if ($categoryImageUrl = $topCategory->getThumbnailUrl()) : ?>
        <div class="innerSectionTitleContent"><img class="selectionTitleImage" src="<?php echo $categoryImageUrl; ?>" alt="" /></div>
    <?php else : ?>
        <strong><span><?php echo $topCategory->getName(); ?></span></strong>
    <?php endif; ?>
</div>

<?php if ($currentCategory->getLevel() == 3) : ?>
    <div class="top-cat-title">
       <!-- <p><?php /*echo $this->__('Overview'); */?></p>-->
        <h1><?php echo $currentCategory->getName(); ?></h1>
        <?php if ($categoryImageUrl = $currentCategory->getImageUrl()) : ?>
            <img src="<?php echo $categoryImageUrl; ?>" width="192" height="147" alt="" />
        <?php endif; ?>
    </div>
<?php elseif ($currentCategory->getLevel() == 2) : ?>
    <div class="top-cat-title">
        <h1>Schmuck-Kollektion <?php echo $currentCategory->getName(); ?></h1>
    </div>
<?php else : ?>
    <div class="sub-cat-title">
        <h1><?php echo $currentCategory->getName(); ?></h1>
        <p class="daily-rates"><?php echo $this->__('Daily rates'); ?></p>
    </div>
<?php endif; ?>

<div class="inner-content subcategory">

<?php if ($currentCategory->getLevel() == 3) : ?>
    <?php $_categories = $currentCategory->getChildrenCategories() ?>
    <?php $_count = is_array($_categories)?count($_categories):$_categories->count(); ?>
    <?php if($_count): ?>
        <ul class="prod-cat">
        <?php foreach ($_categories as $_category) : ?>
            <?php $_subCategory = Mage::getModel('catalog/category')->load($_category->getId()); ?>
            <li>
                <span class="prod-cat-title title-h3"><a href="<?php echo $_subCategory->getUrl(); ?>"><?php echo $_subCategory->getName(); ?></a></span>
                <?php if ($_subCategory->getThumbnailUrl()) : ?><a href="<?php echo $_subCategory->getUrl(); ?>" class="cat-img"><img src="<?php echo $_subCategory->getThumbnailUrl(); ?>" alt="<?php echo $_subCategory->getName(); ?>" /></a><?php endif; ?>
            </li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>

<?php else : ?>

    <?php if ($currentCategory->getLevel() != 2) {
        echo $this->getToolbarHtml();
    } ?>

	<?php
		$block = $this->getLayout()->getBlock('muenzfassungen_info');
		if ($block) {
			echo '<div class="blockUnderCategoryTitle">';
				echo $block->toHtml();
			echo '</div>';
		}
	?>

    <?php if(!$_productCollection->count()): ?>
        <div class="block">
            <div class="inside text-box">
                <p><?php echo $this->__('There are no products matching the selection.') ?></p>
            </div>
        </div>
    <?php else: ?>

        <?php // Grid Mode ?>

            <?php $_collectionSize = $_productCollection->count() ?>
            <?php //$_columnCount = $this->getColumnCount(); ?>
            <?php $_columnCount = 4; ?>

            <ul class="prod-items">
            <?php foreach ($_productCollection as $_product): ?>
                <?php echo $this->getLayout()->createBlock('jewellery_catalog/product_single')
                    ->setTemplate('catalog/product/list_single.phtml')
                    ->setProduct($_product)
                    ->toHtml();
                ?>
            <?php endforeach ?>
            </ul>


    <?php endif; // End collection count ?>

    <div class="page-nav">
    <?php
       // manually get the toolbar block so we can do the page navigation
        $toolbar = $this->getToolbarBlock();
        $toolbar->setCollection($_productCollection);
        if($toolbar->getCollection()->getSize() > 0) {
            echo $toolbar->getPagerHtml();
        }
    ?>
    </div>

<?php endif; // End category level ?>


<?php // Category Description ?>
<?php if($_description=$currentCategory->getDescription()): ?>

    <div class="block">
        <div class="inside small-text">
            <div class="toggle-box">
                <div><?php echo $_helper->categoryAttribute($currentCategory, $_description, 'description') ?></div>
            </div>
            <span id="arrow" class="down-arrow"></span>
        </div>
    </div>
<?php endif; ?>

</div> <!-- end of inner-content block -->



<script>$j("#content").addClass("inner-page");</script>
