<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>

<?php
    //$productName = $_helper->productAttribute($_product, $_product->getName(), 'name');
    //$productShortDescription = $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description');
    //$productDescription = $_helper->productAttribute($_product, nl2br($_product->getDescription()), 'description');
    $productAdditionalDescription = $_helper->productAttribute($_product, nl2br($_product->getAdditionalDescription()), 'additional_description');
?>

<?php //echo $this->getMessagesBlock()->getGroupedHtml() ?>

        <div class="inner-content">

			<?php if ( $searchTerm = Mage::getSingleton('core/session')->getProductSearchQuery() ) : ?>
			<div class='catalogsearch-result-index'>
				<div class="top-cat-title">
					<h2><?php echo $this->__("Bei der Suchanfrage &quot;%s&quot; wurde ein Artikel gefunden.", $searchTerm) ?></h2>
				</div>
				<?php Mage::getSingleton('core/session')->unsProductSearchQuery(); ?>
			</div>
			<?php endif; ?>

            <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>

                <div class="no-display">
                    <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                    <input type="hidden" name="related_product" id="related-products-field" value="" />
                </div>

				<?php $images = $this->getChild('media')->getGalleryImages() ; ?>

                <div class="block prod-desc-full <?php echo sizeof ( $images ) == 1 ? 'prod-desc-full-wide' : ''; ?>">
                    <div class="inside">
                        <h1><?php echo $_helper->productAttribute($_product, $_product->getNameLong(), 'name_long') ?></h1>

                        <?php echo $this->getChildHtml('additional'); ?>

                        <?php echo $this->getChildHtml('description'); ?>

                        <?php //if (!$this->hasOptions()):?>
                            <?php if($_product->isSaleable()): ?>
                                <?php echo $this->getChildHtml('addto') ?>
                              <?php endif; ?>
                        <?php //endif; ?>


                    </div>
                </div>

                <?php echo $this->getChildHtml('media') ?>

                <div class="clear"></div>

				<?php
					$block = $this->getLayout()->getBlock('muenzfassungen_info');
					if ($block) {
						echo '<div class="blockUnderCategoryTitle">';
							echo $block->toHtml();
						echo '</div>';
						echo '<div class="clear"></div>';
					}
				?>

                <div class="block">
                    <div class="inside small-text">
                        <?php if ($_product->getTypeId() == 'configurable') : ?>
                            <?php echo $this->getChildHtml('product.info.producttable'); ?>
                        <?php endif; ?>
                        <?php echo $this->getChildHtml('addtocart') ?>
                        <br class="clear" />
                    </div>
                </div>
                <div class="info-block">
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('product_details_info_block')->toHtml() ?>
                </div>

                <?php if ($productAdditionalDescription) : ?>
                    <div class="block">
                        <div class="inside small-text">
                            <?php echo $productAdditionalDescription; ?>
                        </div>
                    </div>
                <?php endif; ?>

                <?php echo $this->getLayout()->createBlock('awautorelated/blocks')->setBlockId('1')->toHtml() ?>

            </form>

        </div>


    <script>
        //<![CDATA[

        $j("#content").addClass("inner-page").addClass("product-page");

        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
             if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
                return false;
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>


    </script>
