<?php $_product = $this->getProduct(); ?>
<?php $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>


<?php if ($this->helper('wishlist')->isAllow()) : ?>
    <!--<a href="<?php /*echo $_wishlistSubmitUrl */?>" onclick="productAddToCartForm.submitLight(this, '<?php /*echo $_wishlistSubmitUrl */?>'); return false;" class="user-btn-link fr"><?php /*echo $this->__('Add to Wishlist') */?></a>-->
    <a href="<?php echo $_wishlistSubmitUrl ?>" onclick="" class="user-btn-link fr"><?php echo $this->__('Add to Wishlist') ?></a>
<?php endif; ?>

<a href="#product_addtocart_form" class="order-btn" title="<?php echo $this->__('Configure order') ?>"><span><?php echo $this->__('Product order') ?></span><span class="product-order-indicator"></span></a>
