<div class="inner-content order-view">
    <div class="block">
        <div class="inside">
            <h1><?php echo $this->__('My Tags') ?></h1>

            <p class="my-tag-edit">
                <a href="#" title="<?php echo $this->__('Delete') ?>" onclick="if(confirm('<?php echo $this->__('Are you sure you want to delete this tag?') ?>')) window.location='<?php echo $this->getTagInfo()->getRemoveTagUrl(); ?>'; return false;" class="button btn-remove"><span><?php echo $this->__('Delete') ?></span></a>
                <?php echo $this->__('<strong>Tag Name:</strong> %s', $this->htmlEscape($this->getTagInfo()->getName())) ?>
            </p>

            <br class="clear" />

            <?php if( sizeof($this->getMyProducts()) > 0 ): ?>

                <div class="page-nav"><?php echo $this->getToolbarHtml(); ?></div>

                <table class="cart-table">

                    <col width="1" />
                    <col />
                    <col width="1" />
                    <tbody>
                    <?php $iterator = 0 ?>
                    <?php foreach($this->getMyProducts() as $_product): ?>
                        <tr class="<?php echo ($iterator++ % 2 == 0) ? 'odd' : 'even'?>">
                            <td><a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(57,57); ?>" width="57" height="57" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></a></td>

                            <td>
                                <a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a>
                                <?php echo $this->getPriceHtml($_product) ?>
                            </td>

                            <td class="align-center">
                                <?php if($_product->isSaleable()): ?>
                                    <input type="button" class="button-link" title="<?php echo $this->__('Add to Cart') ?>" value="<?php echo $this->__('Add to Cart') ?>" onclick="setLocation('<?php echo $this->getUrl('checkout/cart/add',array('product'=>$_product->getId())) ?>')"/>
                                    <br/><br/>
                                <?php endif; ?>
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <a href="<?php echo $this->getUrl('wishlist/index/add',array('product'=>$_product->getId())) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>

                <div class="page-nav"><?php echo $this->getToolbarHtml(); ?></div>

            <?php else: ?>
                <?php echo $this->__("Unable to find any products tagged with '%s' in the current store", $this->htmlEscape($this->getTagInfo()->getName()) ) ?>
            <?php endif; ?>

            <div class="buttons-set">
                <a class="button-link weiter-link fl" href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" title="<?php echo $this->__('Back to Tags List') ?>"><span><?php echo $this->__('Back to Tags List') ?></span></a>
            </div>

        </div>
    </div>
</div>
